--inspecting data
select * from dbo.sales
-------------------------------------------------------------
--checking unique values
select distinct STATUS FROM DBO.SALES --NICE TO POLT
select distinct YEAR_ID FROM DBO.SALES --NICE TO POLT
select distinct PRODUCTLINE FROM DBO.SALES --NICE TO POLT
select distinct COUNTRY FROM DBO.SALES --NICE TO POLT
select distinct DEALSIZE FROM DBO.SALES --NICE TO POLT
select distinct TERRITORY FROM DBO.SALES --NICE TO POLT
----------------------------------------------------------------
--ANALYSIS
--GROUBING SALES BY MONTHS IN DEFR YEARS
--2005
SELECT MONTH_ID ,CAST(ROUND(SUM(SALES),2) AS DECIMAL(10,2)) AS REVENUE
FROM DBO.SALES
WHERE YEAR_ID = 2005 -- CHANGE YEAR TO SEE THE REST
GROUP BY MONTH_ID
ORDER BY 2 DESC

-------------------------------------------------------------
--GROUBING SALES BY YEARS
SELECT YEAR_ID ,CAST(ROUND(SUM(SALES),2) AS DECIMAL(10,2)) AS REVENUE
FROM DBO.SALES
GROUP BY YEAR_ID
ORDER BY 2 DESC
-------------------------------------------------------------
--GROUBING SALES BY PRODUCTLINE IN DEFR YEARS
--2005
SELECT PRODUCTLINE ,CAST(ROUND(SUM(SALES),2) AS DECIMAL(10,2)) AS REVENUE
FROM DBO.SALES
WHERE YEAR_ID = 2005 -- CHANGE YEAR TO SEE THE REST
GROUP BY PRODUCTLINE
ORDER BY 2 DESC
--------------------------------------------------------------------------
--GROUBING SALES BY PRODUCTLINE  AND COUNTRY IN DEFR YEARS
--2005
SELECT COUNTRY,PRODUCTLINE ,CAST(ROUND(SUM(SALES),2) AS DECIMAL(10,2)) AS REVENUE
FROM DBO.SALES
WHERE YEAR_ID = 2005  -- CHANGE YEAR TO SEE THE REST
GROUP BY COUNTRY,PRODUCTLINE
ORDER BY 1,2 DESC
--------------------------------------------------------------------------

SELECT DEALSIZE ,CAST(ROUND(SUM(SALES),2) AS DECIMAL(10,2)) AS REVENUE
FROM DBO.SALES
GROUP BY DEALSIZE
ORDER BY 2 DESC

SELECT YEAR_ID ,CAST(ROUND(SUM(SALES),2) AS DECIMAL(10,2)) AS REVENUE
FROM DBO.SALES
GROUP BY YEAR_ID
ORDER BY 2 DESC


-----------------------------------------------------------------------------
--WHAT THE BEST MONTH FOR SALES IN SPACIFIC YEAR? HOW MUCH WAS EARND THIS MONTH? 
SELECT MONTH_ID ,
	   CAST(ROUND(SUM(SALES),2) AS DECIMAL(10,2)) AS REVENUE ,
	   COUNT(ORDERNUMBER) AS FREQUENCY
FROM DBO.SALES
WHERE YEAR_ID = 2004  -- CHANGE YEAR TO SEE THE REST
GROUP BY MONTH_ID
ORDER BY 2 DESC
------------------------------------------------------------------------------
-- NOVEMBER SEEMS TO BE THE MONTH, WHAT PRODUCT  DO THEY SELL IN NOVEMBER
SELECT PRODUCTLINE,
	   CAST(ROUND(SUM(SALES),2) AS DECIMAL(10,2)) AS REVENUE ,
	   COUNT(ORDERNUMBER) AS FREQUENCY 
FROM DBO.SALES
WHERE YEAR_ID = 2003 AND MONTH_ID = 11 -- CHANGE YEAR TO SEE THE REST
GROUP BY PRODUCTLINE
ORDER BY 2 DESC
------------------------------------------------------------------------
--WHO IS THE BEST CUSTOMER (THIS COUD BE BEST ANSWERD WITH RFM)?

drop table if EXISTS #RFM
;WITH RFM AS
(
	SELECT 
		CUSTOMERNAME,
		CAST(ROUND(SUM(SALES),2) AS DECIMAL(10,2)) AS MONETARYVALUE,
		CAST(ROUND(AVG(SALES),2) AS DECIMAL(10,2)) AS AVGMONETARYVALUE,
		COUNT(ORDERNUMBER) AS FREQUENCY,
		MAX(ORDERDATE) AS LAST_ORDER,
		(SELECT MAX(ORDERDATE) FROM SALES) AS MAX_ORDER_DATE,
		DATEDIFF(DD,MAX(ORDERDATE),(SELECT MAX(ORDERDATE) FROM SALES)) AS RECENCY
	FROM 
	DBO.sales
	GROUP BY CUSTOMERNAME
),
RFM_CALC AS(
	SELECT * ,
	NTILE(4) OVER (ORDER BY RECENCY DESC) AS RFM_RECENCY,
	NTILE(4) OVER (ORDER BY FREQUENCY) AS RFM_FREQUENCY,
	NTILE(4) OVER (ORDER BY MONETARYVALUE) AS RFM_MONETARYVALUE
	FROM RFM
)
SELECT C.*,
	   RFM_MONETARYVALUE +RFM_FREQUENCY+RFM_RECENCY AS RFM_CELL,
	   CAST(RFM_RECENCY AS varchar(2))+CAST(RFM_FREQUENCY AS varchar(2))+CAST(RFM_MONETARYVALUE AS varchar(2)) rfm_cell_string
INTO #RFM
FROM 
RFM_CALC C
SELECT * FROM #RFM
ORDER BY 10 DESC

SELECT CUSTOMERNAME,
	   RFM_RECENCY,
	   RFM_FREQUENCY,
	   RFM_MONETARYVALUE,
case 
		when rfm_cell_string in (111, 112 , 121, 122, 123, 132, 211, 212, 114, 141,221) then 'lost_customers'  --lost customers
		when rfm_cell_string in (133, 134, 143, 244, 334, 343, 344, 144) then 'slipping away, cannot lose' -- (Big spenders who haven’t purchased lately) slipping away
		when rfm_cell_string in (311, 411, 331,412) then 'new customers'
		when rfm_cell_string in (222, 223, 233, 322,232,234) then 'potential churners'
		when rfm_cell_string in (323, 333,321, 422, 332, 432,421,423) then 'active' --(Customers who buy often & recently, but at low price points)
		when rfm_cell_string in (433, 434, 443, 444) then 'loyal'
end rfm_segment
FROM #RFM

-------------------------------------------------------------------
--WHAT A PRODUCT ARE MOST SOLD TOGETHER?

SELECT DISTINCT ORDERNUMBER, STUFF((
	SELECT ',' + PRODUCTCODE
	FROM protfolioproject.DBO.sales P
	WHERE ORDERNUMBER IN
		(
		SELECT ORDERNUMBER 
		FROM
			(
			SELECT ORDERNUMBER ,COUNT(*) AS NUM_OF_ORDERS
			FROM protfolioproject.DBO.sales
			WHERE STATUS ='Shipped'
			GROUP BY ORDERNUMBER
			) N
		WHERE NUM_OF_ORDERS =2 AND P.ORDERNUMBER =S.ORDERNUMBER -- CHANGE NUM_OF_ORDERS TO SEE THE REST
		)
		FOR XML PATH('')),1,1,'') PRODUCTCODES
FROM protfolioproject.DBO.sales S
ORDER BY 2 DESC

